### ISSUE TITLE
cloud account parameter in wizard app

### ISSUE THREAD

**Issue by fjcoira** [ingrammicro/concerto#7] opened 2017-05-02 15:11 UTC
In master branch, cloud provider is still used, but Concerto 5.0.0 > uses cloud account as parameter.

This feature has to be updated (wizard/apps/subcommands.go).

**Comment by fjcoira** [comment] 2017-05-02 15:14
Also, it should provide a new command "cloud_accounts" (instead of wizard/cloud_providers/subcommands.go).

**Comment by pbanos** [comment] 2018-02-20 13:53
Duplicate of #3

**Closed by pbanos** 2018-02-20 13:53 UTC
Labels: bug
